### ISSUE TITLE
[Question] Why disabling tests on CI?

### ISSUE THREAD

**Issue by olivierobert** [Prabeshpd/web-scraper-backend#15]
## Issue

While there are automated tests implemented for three endpoints, the tests are disabled by a conditional block:

https://github.com/Prabeshpd/web-scraper-backend/blob/e56ce8af7d018a07849632cf7f5358c827871b84/test/api/user.spec.ts#L7-L12

## Expected

Automated tests should be executable in both local and remote (such as CI server) environments.

**Comment by Prabeshpd** [comment]
Ideally, I would create a docker compose file for test build file and database instance with scripts to create a database and run the seed script and then run the automated tests. Since, there was limited time I have added an environment variable in assumption that there is a database instance already available. In the CI environment there is no provision of creating a database instance I am commenting it out for now. But in the production ready code I would have those scripts in place and the docker file to up the instance of database and they would not be disabled.

**Comment by olivierobert** [comment]
Since GitHub Actions is used, you could set a DB instance on the CI environment:

```
    services:
      db:
        image: postgres:14.8
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
```

See [the docs](https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers) for more information.

**Comment by Prabeshpd** [comment]
I set up the DB instance using the service feature of GitHub action. Now, test is enabled on CI environment as well. I used to create a separate docker compose file for this really helpful. Have been missing on this.
